# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mahdi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import numpy as np
import neuralNetworks


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 200)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setGeometry(QtCore.QRect(30, 10, 16, 20))
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(90, 10, 16, 20))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(120, 10, 16, 20))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(150, 10, 16, 20))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 40, 16, 20))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(60, 40, 16, 20))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(90, 40, 16, 20))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(120, 40, 16, 20))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(150, 40, 16, 20))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(30, 70, 16, 20))
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(60, 70, 16, 20))
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setGeometry(QtCore.QRect(90, 70, 16, 20))
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setGeometry(QtCore.QRect(120, 70, 16, 20))
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setGeometry(QtCore.QRect(150, 70, 16, 20))
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_16.setGeometry(QtCore.QRect(30, 100, 16, 20))
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_17.setGeometry(QtCore.QRect(60, 100, 16, 20))
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_18.setGeometry(QtCore.QRect(90, 100, 16, 20))
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_19.setGeometry(QtCore.QRect(120, 100, 16, 20))
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_20.setGeometry(QtCore.QRect(150, 100, 16, 20))
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_21.setGeometry(QtCore.QRect(30, 130, 16, 20))
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_22.setGeometry(QtCore.QRect(60, 130, 16, 20))
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_23.setGeometry(QtCore.QRect(90, 130, 16, 20))
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_24.setGeometry(QtCore.QRect(120, 130, 16, 20))
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_25.setGeometry(QtCore.QRect(150, 130, 16, 21))
        self.checkBox_25.setText("")
        self.checkBox_25.setObjectName("checkBox_25")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(200, 80, 93, 28))
        self.pushButton_1.setObjectName("pushButton")
        self.pushButton_1.clicked.connect(
            lambda: self.setBtnClicked(
                self.checkBox_1,
                self.checkBox_2,
                self.checkBox_3,
                self.checkBox_4,
                self.checkBox_5,
                self.checkBox_6,
                self.checkBox_7,
                self.checkBox_8,
                self.checkBox_9,
                self.checkBox_10,
                self.checkBox_11,
                self.checkBox_12,
                self.checkBox_13,
                self.checkBox_14,
                self.checkBox_15,
                self.checkBox_16,
                self.checkBox_17,
                self.checkBox_18,
                self.checkBox_19,
                self.checkBox_20,
                self.checkBox_21,
                self.checkBox_22,
                self.checkBox_23,
                self.checkBox_24,
                self.checkBox_25,
            )
        )

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(200, 40, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 40, 93, 28))
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 80, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(
            lambda: self.preBtnClicked(
                self.checkBox_1,
                self.checkBox_2,
                self.checkBox_3,
                self.checkBox_4,
                self.checkBox_5,
                self.checkBox_6,
                self.checkBox_7,
                self.checkBox_8,
                self.checkBox_9,
                self.checkBox_10,
                self.checkBox_11,
                self.checkBox_12,
                self.checkBox_13,
                self.checkBox_14,
                self.checkBox_15,
                self.checkBox_16,
                self.checkBox_17,
                self.checkBox_18,
                self.checkBox_19,
                self.checkBox_20,
                self.checkBox_21,
                self.checkBox_22,
                self.checkBox_23,
                self.checkBox_24,
                self.checkBox_25,
            )
        )

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 120, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(
            lambda: self.clearBtnClicked(
                self.checkBox_1,
                self.checkBox_2,
                self.checkBox_3,
                self.checkBox_4,
                self.checkBox_5,
                self.checkBox_6,
                self.checkBox_7,
                self.checkBox_8,
                self.checkBox_9,
                self.checkBox_10,
                self.checkBox_11,
                self.checkBox_12,
                self.checkBox_13,
                self.checkBox_14,
                self.checkBox_15,
                self.checkBox_16,
                self.checkBox_17,
                self.checkBox_18,
                self.checkBox_19,
                self.checkBox_20,
                self.checkBox_21,
                self.checkBox_22,
                self.checkBox_23,
                self.checkBox_24,
                self.checkBox_25,
            )
        )

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 120, 93, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 10, 221, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Character recognition"))
        self.pushButton_1.setText(_translate("MainWindow", "SET"))
        self.label.setText(_translate("MainWindow", "OUTPUT"))
        self.pushButton_2.setText(_translate("MainWindow", "PREDICTION"))
        self.pushButton_3.setText(_translate("MainWindow", "CLEAR"))
        self.textEdit.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.comboBox.setItemText(0, _translate("MainWindow", "Hebb"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Perceptron"))
        self.comboBox.setItemText(2, _translate("MainWindow", "MCPerceptron"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Adaline"))
        self.comboBox.setItemText(4, _translate("MainWindow", "MCAdaline"))
        self.label_2.setText(_translate("MainWindow", "Welcome to the program."))

    def setBtnClicked(self, *x):
        file1 = open("xoData.txt", "a")

        self.dataList = []
        for b in x:
            if b.isChecked() == True:
                self.dataList.append(1)
            else:
                self.dataList.append(-1)

        if self.textEdit.toPlainText().lower() == "x":
            self.dataList.append(1)
            string = " ".join(str(i) for i in self.dataList) + "\n"
            file1.write(string)
            file1.close()
            self.label_2.setText("Your data saved.")
        elif self.textEdit.toPlainText().lower() == "o":
            self.dataList.append(-1)
            string = " ".join(str(i) for i in self.dataList) + "\n"
            file1.write(string)
            file1.close()
            self.label_2.setText("Your data saved.")
        else:
            self.label_2.setText("Your data is not valid!!!")

    def preBtnClicked(self, *x):
        self.dataList = []
        for b in x:
            if b.isChecked() == True:
                self.dataList.append(1)
            else:
                self.dataList.append(-1)

        if self.comboBox.currentIndex() == 0:
            self.label.setText(
                "X"
                if neuralNetworks.calculate_output(
                    np.array([self.dataList]), weightsHebb, biasHebb
                )
                == 1
                else "O"
            )

        elif self.comboBox.currentIndex() == 1:
            self.label.setText(
                "X"
                if neuralNetworks.calculate_output(
                    np.array([self.dataList]), weightsPerceptron, biasPerceptron
                )
                == 1
                else "O"
            )


        elif self.comboBox.currentIndex() == 2:
            x = neuralNetworks.calculate_output(
                np.array([self.dataList]), weightsMultiClassPerceptron[0], biasMultiClassPerceptron[0]
            )
            o = neuralNetworks.calculate_output(
                np.array([self.dataList]), weightsMultiClassPerceptron[1], biasMultiClassPerceptron[1]
            )

            if x == 1 and o == -1:
                self.label.setText("X")
            elif o == 1 and x == -1:
                self.label.setText("O")
            else:
                self.label.setText("Other shape")


        elif self.comboBox.currentIndex() == 3:
            self.label.setText(
                "X"
                if neuralNetworks.calculate_output(
                    np.array([self.dataList]), weightsAdaline, biasAdaline
                )
                == 1
                else "O"
            )


        elif self.comboBox.currentIndex() == 4:
            x = neuralNetworks.calculate_output(
                np.array([self.dataList]), weightsMultiClassAdaline[0], biasMultiClassAdaline[0]
            )
            o = neuralNetworks.calculate_output(
                np.array([self.dataList]), weightsMultiClassAdaline[1], biasMultiClassAdaline[1]
            )

            if x == 1 and o == -1:
                self.label.setText("X")
            elif o == 1 and x == -1:
                self.label.setText("O")
            else:
                self.label.setText("Other shape")

    def clearBtnClicked(self, *x):
        for i in x:
            i.setChecked(False)

        self.textEdit.setText("")
        self.label.setText("OUTPUT")
        self.label_2.setText("Welcome to the program.")
        _translate = QtCore.QCoreApplication.translate
        self.textEdit.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )


if __name__ == "__main__":
    import sys

    weightsHebb, biasHebb = neuralNetworks.hebb()
    weightsPerceptron, biasPerceptron = neuralNetworks.perceptron()
    weightsMultiClassPerceptron, biasMultiClassPerceptron = neuralNetworks.multiClassPerceptron()
    weightsAdaline, biasAdaline = neuralNetworks.adaline()
    weightsMultiClassAdaline, biasMultiClassAdaline = neuralNetworks.multiClassAdaline()

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
